name: Build and test
on:
  pull_request:
  push:
    paths-ignore:
      - '**.md'
      - 'LICENSE'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        type: [debug, release]
    steps:

    - name: checkout code
      uses: actions/checkout@v4

    - name: install black
      run: pip install black

    - name: check format
      run: python3 scripts/format.py --path src --check

    - name: install xmake
      uses: xmake-io/github-action-setup-xmake@v1
      with:
        xmake-version: latest

    - name: configure xmake
      run: xmake f -cv

    - name: build with xmake
      run: xmake build && xmake install
